name: "Daily update of Chrome DevTools Protocol"
on:
  schedule:
    # Every night at 4am
    - cron: "0 4 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Update protocol
        run: kotlinc -script update-protocol.kts

      - name: Read protocol version
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: protocol/version.txt
          trim: true

      - name: Create pull-request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Update Chrome DevTools Protocol definitions to ${{ steps.version.outputs.text }}"
          body: "This is an automated PR."
          branch: "protocol-update"
          path: "protocol/"
          commit-message: "Update Chrome DevTools Protocol definitions to ${{ steps.version.outputs.text }}"